plugins:
  demonstrator_enabled:
    default: true
    client: true
  demonstrator_group:
    type: text
    client: true
    default: "demonstrator"
  demonstrator_manager_group:
    type: text
    client: true
    default: ""
  demonstrator_removed_group:
    type: text
    client: true
    default: ""
  demonstrator_category:
    type: text
    client: true
    default: "demonstrator"
  demonstrator_ucf:
    type: text
    client: true
    default: "user_field_1"
